;; The code that comes with the exercise:
(define (cube x) (* x x x))

(define (p x)
  (write 'a) ;; I cheekily inserted this here and just counted the 'a's.
  (- (* 3 x) (* 4 (cube x))))

(define (sine angle)
  (if (not (> (abs angle) 0.1))
      angle
      (p  (sine (/ angle 3.0)))))
;; a. How many times is the procedure p applied when (sine 12.15) is evaluated?
;; 5

;; "When you don't see the solution, do it mechanically..", so doing this on paper will give that same result quickly.

;; b. What is the order of growth in space and number of steps (as a function of a) used by the process generated by the sine procedure when (sine a) is evaluated?

;; This is a little harder to do.
;; It's going to be lower than n, because it's not advancing as much as the solutions are:

;; 10> (sine 1)
;; aaa0.841594565005584
;; #;11> (sine 5)
;; aaaa-0.958017156567296
;; #;12> (sine 25)
;; aaaaaa-0.127490515550731

;; the angle is getting divided by 3 every step, I don't know what kind of formula that is.
;; The math is not strong in this one anymore :/

;; Moving on.
