;; The code that comes with the exercise:
(define (cube x) (* x x x))

(define (p x)
  (write ".") ;; I cheekily inserted this here and just counted the dots.
  (- (* 3 x) (* 4 (cube x))))

(define (sine angle)
  (if (not (> (abs angle) 0.1))
      angle
      (p  (sine (/ angle 3.0)))))
;; a. How many times is the procedure p applied when (sine 12.15) is evaluated?
;; 5

;; "When you don't see the solution, do it mechanically..", so doing this on paper will give that same result quickly.

;; b. What is the order of growth in space and number of steps (as a function of a) used bu the process generated by the sine procedure when (sine a) is evaluated?

;; This is a little harder to do.
;; 
